/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QBar: typeof import('quasar')['QBar']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QDate: typeof import('quasar')['QDate']
    QDialog: typeof import('quasar')['QDialog']
    QDrawer: typeof import('quasar')['QDrawer']
    QFooter: typeof import('quasar')['QFooter']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QMarkupTable: typeof import('quasar')['QMarkupTable']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QRadio: typeof import('quasar')['QRadio']
    QScrollArea: typeof import('quasar')['QScrollArea']
    QSelect: typeof import('quasar')['QSelect']
    QSpace: typeof import('quasar')['QSpace']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    QTooltip: typeof import('quasar')['QTooltip']
    QUploader: typeof import('quasar')['QUploader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
